export const RESET_GAME = "RESET_GAME";
export const SELECT_TILE = "SELECT_TILE";
export const UPDATE_CARD_STATE = "UPDATE_CARD_STATE";
export const COMPLETED = "COMPLETED";
export const UPDATE_CLICK_STATE = "UPDATE_CLICK_STATE";
