export const CardType = {
  Diamond: "diamond",
  Plane: "paper-plane-o",
  Anchor: "anchor",
  Bolt: "bolt",
  Cube: "cube",
  Leaf: "leaf",
  Bicycle: "bicycle",
  Bomb: "bomb",
};

export const CardTy = {
  Diamond: "diamond",
  Plane: "paper-plane-o",
  Anchor: "anchor",
  Bolt: "bolt",
  Cube: "cube",
  Leaf: "leaf",
  Bicycle: "bicycle",
  Bomb: "bomb",
  Check: "check",
  Signal: "signal",
  Cog: "cog",
  Book: "book",
  Eye: "eye",
  Plane: "plane",
  Twitter: "twitter",
  Truck: "truck",
  Gavel: "gavel",
  Gamepad: "gamepad",
  Github: "github-alt",
};
